---
name: Parchment
main: com.basicer.parchment.bukkit.ParchmentPlugin
version: 0.1
softdepend: [ProtocolLib]
commands:
  parchment:
    description: Debug commands for parchment.
    aliases: [p]
    usage: §f[§eP§archment§f]§r Command Failed.
  cast:
    aliases: [c]
    description: Shortcut for /parchment cast
    usage: §f[§eP§archment§f]§r Command Failed.
