---
name: Parchment
main: com.basicer.parchment.bukkit.ParchmentPlugin
version:  ${project.version} (build ${BUILD_NUMBER})
softdepend: [ProtocolLib, Spout]
commands:
  parchment:
    description: Debug commands for parchment.
    aliases: [p]
    usage: §f[§eP§rarchment§f]§r Command Failed.
  cast:
    aliases: [c]
    description: Shortcut for /parchment cast
    usage: §f[§eP§rarchment§f]§r Command Failed.
  scriptmode:
    description: Enter script mode.
    usage: §f[§eP§rarchment§f]§r Command Failed.